global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "churn-api"
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "fluentbit-logs"
    static_configs:
      - targets: ["host.docker.internal:2020"]  # nếu dùng Fluent Bit metrics

  # GPU monitoring (nếu có)
  - job_name: "gpu_exporter"
    static_configs:
      - targets: ["host.docker.internal:9400"]
  - job_name: 'fastapi_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8000']  # hoặc IP/container của API
  